from gym.spaces import Box, Dict, Discrete, Tuple

SEED = 1
NUM_STEPS = 5

DISCRETE_VALUE = 1

BOX_LOW, BOX_HIGH, BOX_DIM = -5, 5, (10, 10)

NEW_BOX_DIM = (100, 1)
NEW_BOX_DIM_IMPOSSIBLE = (99,)

TESTING_BOX_OBSERVATION_SPACE = Box(BOX_LOW, BOX_HIGH, BOX_DIM)

